models/Usuario.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "usuario".
 *
 * @property int $id
 * @property string $username
 * @property string $nome_completo
 * @property string $cpf
 * @property string $email
 * @property string $telefone
 * @property string $authKey
 * @property string $password
 * @property string $password_reset_token
 * @property string $user_level
 * @property int $orgao_id
 * @property string $accessToken
 *
 * @property Log[] $logs
 * @property Observacao[] $observacaos
 * @property Operacao[] $operacaos
 * @property Orgao $orgao
 * @property UserLvl $userLvlDi
 */
class Usuario extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'usuario';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nome_completo','password','cpf','orgao_id'], 'required', 'message'=>'Campo não pode ser em branco'],
            [['orgao_id'], 'integer'],
            [['cpf'],'unique'],
            [['accessToken'], 'string'],
            [['username', 'cpf', 'email', 'telefone', 'authKey', 'password', 'password_reset_token', 'user_level'], 'string', 'max' => 45],
            [['nome_completo'], 'string', 'max' => 200],
            [['orgao_id'], 'exist', 'skipOnError' => true, 'targetClass' => Orgao::className(), 'targetAttribute' => ['orgao_id' => 'id']]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Usuário (Como devo chamá-lo(a))',
            'nome_completo' => 'Nome Completo',
            'cpf' => 'CPF',
            'email' => 'E-mail',
            'telefone' => 'Telefone',
            'authKey' => 'Auth Key',
            'password' => 'Senha',
            'password_reset_token' => 'Password Reset Token',
            'user_level' => 'User Level',
            'orgao_id' => 'Órgão',
            'accessToken' => 'Access Token'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLogs()
    {
        return $this->hasMany(Log::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObservacaos()
    {
        return $this->hasMany(Observacao::className(), ['usuario_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOperacaos()
    {
        return $this->hasMany(Operacao::className(), ['usuario_responsavel_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrgao()
    {
        return $this->hasOne(Orgao::className(), ['id' => 'orgao_id']);
    }
}

controllers/UsuarioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Usuario;
use yii\filters\AccessControl;
use app\models\UsuarioSearch;
use app\models\Logincerebrum;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsuarioController implements the CRUD actions for Usuario model.
 */
class UsuarioController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout','create','index','delete','update','solicitacaodeacesso'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login','getusuario','solicitacaodeacesso'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create','view','index','delete','update'],
                        'matchCallback' => function($rule,$action){
                                if(!Yii::$app->user->isGuest){
                                    if(Yii::$app->user->identity->user_lvl != Logincerebrum::USUARIO_COMUM){
                                        return true;
                                    }else{
                                        return false;
                                    }
                                }
                            },
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Usuario models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsuarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Usuario model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        $login = Logincerebrum::find()->where(['usuario_id'=>$id])->one();
        
        return $this->render('view-novo', [
            'model' => $this->findModel($id),
            'login' => $login
        ]);
    }
    
    /**
     * Creates a new Usuario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionSolicitacaodeacesso()
    {
        $model = new Usuario();
        $login = new Logincerebrum();
        $mensagem = '';
        

        if(Yii::$app->request->post()){
            
            $model->load(Yii::$app->request->post());
            $login->load(Yii::$app->request->post());

            // monta objeto login 
            $login->username = $model->username;
            $login->status_acesso = Logincerebrum::STATUS_INATIVO;
            $login->cpf = $model->cpf;
            $login->password = $model->password;
            $login->user_lvl = Logincerebrum::USUARIO_COMUM;

            $usuario_existente = Usuario::find()->where(['cpf'=>$model->cpf])->one();
            if($usuario_existente){
                
                $mensagem = 'errocpf';
                return $this->render('create', [
                    'model' => $model,
                    'mensagem' => $mensagem
                ]);
            }
            
            $transaction = Yii::$app->db->beginTransaction();
            try {
                if ($model->save()) {
                    $login->usuario_id = $model->id;
    
                    if($login->save()){
                        $transaction->commit();
                        $mensagem = 'sucesso';
                        return $this->redirect(['site/index', 'mensagem' => $mensagem]);
                    }
                }
            } catch (\Throwable $th) {
                $transaction->rollBack();
            }
        }

        return $this->render('create', [
            'model' => $model,
            'mensagem' => $mensagem
        ]);
    }

    /**
     * Creates a new Usuario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Usuario();
        $login = new Logincerebrum();
        $mensagem = '';
        if(Yii::$app->request->post()){
            
            $model->load(Yii::$app->request->post());
            $login->load(Yii::$app->request->post());
            // monta objeto login 
            $login->username = $model->username;
            $login->status_acesso = Logincerebrum::STATUS_ATIVO;
            $login->cpf = $model->cpf;
            $login->password = $model->password;

            $transaction = Yii::$app->db->beginTransaction();

            try {
                if ($model->save()) {
                    $login->usuario_id = $model->id;
    
                    if($login->save()){
                        $transaction->commit();
                        $mensagem = 'sucesso';
                        return $this->redirect(['view', 'id' => $model->id, 'mensagem'=>$mensagem]);
                    }
                }
            } catch (\Throwable $th) {
                $transaction->rollBack();
                $mensagem = 'erro';
            }
        }

        return $this->render('create', [
            'model' => $model,
            'mensagem' => $mensagem
        ]);
    }

    /**
     * Updates an existing Usuario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $login = Logincerebrum::find()->where(['usuario_id'=>$id])->one();
        $mensagem = "sucesso";

        if(Yii::$app->request->post()){

            $model->load(Yii::$app->request->post());
            $login->load(Yii::$app->request->post());

            $transaction = Yii::$app->db->beginTransaction();
            try {
                if($model->save()){
                    $login->username = $model->username;
                    $login->cpf = $model->cpf;
                    $login->password = $model->password;

                    if($login->save()){
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id, 'mensagem'=>$mensagem]);
                    }else{
                        $mensagem = "erro";
                    }
                }else{
                    $mensagem = "erro";
                }
            } catch (\Throwable $th) {
                $transaction->rollBack();
            }   
        }

        return $this->render('update', [
            'model' => $model,
            'login' => $login
        ]);
    }

    /**
     * Deletes an existing Usuario model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } catch (\Throwable $th) {
            //throw $th;
        }
        return $this->redirect(['index','status'=>'400','message'=>'não foi possivel excluir']);
        
    }

    public function actionGetusuario(){
        if(Yii::$app->request->get()){

            $usuario = new Usuario();
            $data = null;
            
            try {
                if(Yii::$app->request->get('id')){
                    $id = Yii::$app->request->get('id');
                    $usuario->id = $id;
                    $usuario = Usuario::findOne($usuario->id);
                    if($usuario){
                        $data = [
                            'cpf'=>$usuario->cpf,
                            'username'=>$usuario->username
                        ];
                    }
                    return json_encode(['message'=>'sucesso','data'=>$data,'status'=>200]);
                }else{
                    return json_encode(['message'=>'informação incorreta','data'=>'','status'=>400]);
                }
            } catch (\Throwable $th) {
                return json_encode(['message'=>'Usuario não encontrado','data'=>'','status'=>400]);
            }
            
        }
        return json_encode(['message'=>'Usuario não encontrado fora','data'=>'','status'=>400]);
    }

    // Caso haja novamente uma perca de dados do servidor, é só executar esse método para recriar os logins
    // public function actionCrialogins(){
    //     $usuarios = Usuario::find()->all();
    //     $cont = 0;
    //     foreach($usuarios as $usuario){
    //         $login = new Logincerebrum();
    //         $login->attributes = $usuario->attributes;
    //         $login->usuario_id = $usuario->id;
    //         $login->user_lvl = Logincerebrum::USUARIO_COMUM;
    //         $login->status_acesso = Logincerebrum::STATUS_ATIVO;
    //         if($login->save()){
    //             $cont++;
    //             echo "<pre>"; print_r("salvou ".$cont);
    //         }else{
    //             echo "<pre>"; print_r("não salvou ".$usuario->cpf);
    //         }
    //     }
        
    //     echo "<pre>"; print_r(count($usuarios));die;
    //     return null;
    // }

    /**
     * Finds the Usuario model based on its primary key value.

views/usuario/_form-alterar.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Orgao;
use app\models\Logincerebrum;
use app\models\Userlvl;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin(); ?>

        <fieldset>
            <Legend><h1>Alterar Usuário</h1></legend>

            <div class="col-md-12">

                <div class="col-md-6">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'nome_completo')->textInput(['maxlength' => true]) ?>
                    
                    <div class="form-group field-usuario-cpf required">
                        <label class="control-label" for="usuario-cpf">CPF</label>
                        <input type="text" value="<?php echo $model->cpf; ?>" id="usuario-cpf" class="form-control cpf" name="Usuario[cpf]" maxlength="45" aria-required="true" aria-invalid="true">
                    </div>

                    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                    
                </div>
                <div class="col-md-6">
                    <div class="form-group field-usuario-telefone">
                        <label class="control-label" for="usuario-telefone">Telefone</label>
                        <input type="text" value="<?php echo $model->telefone; ?>" id="usuario-telefone" class="form-control telefone" name="Usuario[telefone]" maxlength="45" aria-invalid="false">
                    </div>


                    <?php 
                    // verificação de campo habilitado ou não por nivel de acesso
                        $alterar_orgao_desabilitado = true;
                        $alterar_status_login_desabilitado = true;

                        if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                            $alterar_orgao_desabilitado = false;
                            $alterar_status_login_desabilitado = false;
                        }
                        if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO && Logincerebrum::mesmoOrgao($model->id)){
                            $alterar_status_login_desabilitado = false;
                        }

                    ?>
                    <?= $form->field($model, 'orgao_id')
                        ->dropDownList(
                            ArrayHelper::map(Orgao::find()->all(), 'id', 'sigla'),         // Flat array ('id'=>'label')
                            ['prompt'=>'Selecione ','name'=>'Usuario[orgao_id]', 'disabled'=>$alterar_orgao_desabilitado]    // options
                    ); ?>

                    <?php 
                        if(!Yii::$app->user->isGuest){
                            if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                                echo  $form->field($login, 'user_lvl')->dropDownList(Logincerebrum::TIPOS_USUARIOS,['value'=>$login->user_lvl])->label('Tipo de Usuário'); 
                            }
                            if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO){
                                echo  $form->field($login, 'user_lvl')->dropDownList(Logincerebrum::TIPOS_USUARIOS_POR_ORGAO,['value'=>$login->user_lvl])->label('Tipo de Usuário'); 
                            }
                        }
                    ?>

                    <div class="form-group field-operacao-latitude">
                        <label class="control-label" for="operacao-latitude">Acesso</label>
                        <?php echo $form->field($login, 'status_acesso')->dropDownList(Logincerebrum::STATUS_ACESSO,['disabled'=>$alterar_status_login_desabilitado])->label(false); ?>
                    </div>

                    <?php
                        if(Yii::$app->user->identity->usuario_id == $model->id || Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                            echo $form->field($model, 'password')->passwordInput(['maxlength' => true]);
                        }                     
                     ?>
                     
                </div>

            </div>

        </fieldset>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script src="../js/jquery-3.3.1.min.js" ></script>
<script src="../js/jquery.maskedinput.min.js" ></script>
<script>
    $(document).ready(function($){
        $('.cpf').mask("999.999.999-99");
        $('.telefone').mask("(99)99999-9999");
        
    })
</script>

views/usuario/_form-novo.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Orgao;
use app\models\Logincerebrum;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin(); ?>

        <fieldset>
            <Legend><h1>Criar Usuário</h1></legend>

            <div class="col-md-12">

                <div class="col-md-6">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'nome_completo')->textInput(['maxlength' => true]) ?>

                    <?php //echo $form->field($model, 'cpf')->textInput(['maxlength' => true]) ?>

                    <div class="form-group field-usuario-cpf required">
                        <label class="control-label" for="usuario-cpf">CPF</label>
                        <input type="text" id="usuario-cpf" class="form-control cpf" name="Usuario[cpf]" maxlength="45" aria-required="true" aria-invalid="true">
                    </div>

                    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                    
                </div>
                <div class="col-md-6">
                    <?php //echo $form->field($model, 'telefone')->textInput(['maxlength' => true]) ?>
                    <div class="form-group field-usuario-telefone">
                        <label class="control-label" for="usuario-telefone">Telefone</label>
                        <input type="text" id="usuario-telefone" class="form-control telefone" name="Usuario[telefone]" maxlength="45" aria-invalid="false">
                    </div>

                    <?= $form->field($model, 'orgao_id')
                        ->dropDownList(
                            ArrayHelper::map(Orgao::find()->all(), 'id', 'sigla'),         // Flat array ('id'=>'label')
                            ['prompt'=>'Selecione ','name'=>'Usuario[orgao_id]']    // options
                    ); ?>

                    <?php 
                        if(!Yii::$app->user->isGuest){
                            if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                                echo  $form->field($login = new Logincerebrum(), 'user_lvl')->dropDownList(Logincerebrum::TIPOS_USUARIOS,['value'=>'COMUM'])->label('Tipo de Usuário'); 
                            }
                            if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO){
                                echo  $form->field($login = new Logincerebrum(), 'user_lvl')->dropDownList(Logincerebrum::TIPOS_USUARIOS_POR_ORGAO,['value'=>'COMUM'])->label('Tipo de Usuário'); 
                            }
                        }
                    ?>

                    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
                </div>

            </div>

        </fieldset>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script src="../js/jquery-3.3.1.min.js" ></script>
<script src="../js/jquery.maskedinput.min.js" ></script>
<script>

    let msg = "<?php echo $mensagem; ?>";

    function verificamsg(msg){
        if(msg){
            if(msg == "errocpf"){
                sweetAlert('CPF ja cadastrado!','Entre em contato para mais informações','warning');
            }
        }
    }
    $(document).ready(function($){
        $('.cpf').mask("999.999.999-99");
        $('.telefone').mask("(99)99999-9999");
        verificamsg(msg);
    })
</script>

views/usuario/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nome_completo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'telefone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'authKey')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_reset_token')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'user_level')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'orgao_id')->textInput() ?>

    <?= $form->field($model, 'accessToken')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usuario/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */

// $this->title = 'Create Usuario';
// $this->params['breadcrumbs'][] = ['label' => 'Usuarios', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuario-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form-novo', [
        'model' => $model,
        'mensagem' => $mensagem
    ]) ?>

</div>

views/usuario/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\Orgao;
use app\models\Logincerebrum;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Usuários';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuario-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Cadastrar Usuário', ['create'], ['class' => 'btn btn-success']) ?> 
        <?php //echo Html::a('Conceder acesso', ['logincerebrum/create'], ['class' => 'btn btn-info']) ?> 
    </p>

    <?= 
    // GridView::widget([
    //     'dataProvider' => $dataProvider,
    //     'filterModel' => $searchModel,
    //     'columns' => [
    //         ['class' => 'yii\grid\SerialColumn'],

    //         // 'id',
    //         'username',
    //         // 'nome_completo',
    //         'cpf',
    //         'email:email',
    //         //'telefone',
    //         //'authKey',
    //         //'password',
    //         //'password_reset_token',
    //         //'user_level',
    //         'orgao_id',
    //         //'accessToken:ntext',
    //         //'user_lvl_di',

    //         ['class' => 'yii\grid\ActionColumn'],
    //     ],
    // ]); 
    
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'contentOptions' => ['style' => 'width: 20px;', 'class' => 'text-center'],
            ],
            [
                'attribute' => 'username',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['style' => 'width: 30%; color:#337ab7;', 'class' => 'text-left'],
            ],
            [
                'attribute' => 'cpf',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
            ],    
            [
                'attribute' => 'orgao_id',
                'headerOptions' => ['class' => 'text-center'],
                'value'  => function ($data) {
                    return Orgao::findOne($data->orgao_id)->sigla;
                },
                'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
            ],            
            [
            'class' => 'yii\grid\ActionColumn',
            'header'=>'Ações', 
            'headerOptions' => ['width' => '80','style'=>'width: 20%; color:#337ab7;', 'class'=>'text-center'],
            'template' => '{view} {alterar} {acesso} {deletar}',
            'buttons' => [
                    'view' => function($url,$model,$key){
                            return Html::a('<div class="btn btn-info" onclick="loading()">Visualizar</div>', Url::to(['usuario/view','id'=>$key]));
                        
                    },
                    'alterar' => function($url,$model,$key){
                        if(Yii::$app->user->identity->orgao_id == 23){
                            return Html::a('<div class="btn btn-warning" onclick="loading()">alterar</div>', Url::to(['usuario/update','id'=>$key]));
                        }
                    },
                    'acesso' => function($url,$model,$key){

                        if(Yii::$app->user->identity->user_lvl != Logincerebrum::USUARIO_COMUM){
                            $acesso = Logincerebrum::verificaSeUsuarioTemAcesso($key);
                            if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                                if($acesso == Logincerebrum::STATUS_INATIVO){
                                    return Html::a('<div class="btn btn-danger" onclick="loading()">Inativo</div>', Url::to(['logincerebrum/mudarstatus','id'=>$key]));
                                }else{
                                    return Html::a('<div class="btn btn-success" onclick="loading()">Ativo</div>', Url::to(['logincerebrum/mudarstatus','id'=>$key]));
                                }
                            }else if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO){
                                $login = Logincerebrum::find()->where(['usuario_id'=>$model->id])->one();
                                if($login->user_lvl != Logincerebrum::USUARIO_ADM){
                                    if($acesso == Logincerebrum::STATUS_INATIVO){
                                        return Html::a('<div class="btn btn-danger" onclick="loading()">Inativo</div>', Url::to(['logincerebrum/mudarstatus','id'=>$key]));
                                    }else{
                                        return Html::a('<div class="btn btn-success" onclick="loading()">Ativo</div>', Url::to(['logincerebrum/mudarstatus','id'=>$key]));
                                    }
                                }
                            }
                            
                            
                        }
                    },
                ],
            ],
        ],
    ]); 
    
    
    ?>
</div>

views/usuario/view-novo.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Orgao;
use app\models\Logincerebrum;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Usuario */
/* @var $form yii\widgets\ActiveForm */
$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Usuários', 'url' => ['index']];
?>

<div class="usuario-form">

    <?php $form = ActiveForm::begin(); ?>

        <fieldset>
            <Legend><h1>Visualizar Usuário</h1></legend>

            <div class="col-md-12">

                <div class="col-md-6">
                    <?= $form->field($model, 'username')->textInput(['maxlength' => true,'disabled'=>true]) ?>

                    <?= $form->field($model, 'nome_completo')->textInput(['maxlength' => true,'disabled'=>true]) ?>

                    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true,'disabled'=>true]) ?>

                    <?= $form->field($model, 'email')->textInput(['maxlength' => true,'disabled'=>true]) ?>
                    
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'telefone')->textInput(['maxlength' => true,'disabled'=>true]) ?>

                    <?= $form->field($model, 'orgao_id')
                        ->dropDownList(
                            ArrayHelper::map(Orgao::find()->all(), 'id', 'sigla'),         // Flat array ('id'=>'label')
                            ['prompt'=>'Selecione ','name'=>'Usuario[orgao_id]', 'disabled'=>true]    // options
                    ); ?>

                    <div class="form-group field-operacao-latitude">
                        <label class="control-label" for="operacao-latitude">Tipo de Usuario</label>
                        <?= $form->field($login, 'user_lvl')->textInput(['maxlength' => true,'disabled'=>true])->label(false) ?>
                    </div>

                    <div class="form-group field-operacao-latitude">
                        <label class="control-label" for="operacao-latitude">Acesso</label>
                        <?php echo $form->field($login, 'status_acesso')->dropDownList(Logincerebrum::STATUS_ACESSO,['value'=>$login->status_acesso,'disabled'=>true])->label(false); ?>
                    </div>

                </div>

            </div>

            <?php echo Html::a('<div class="btn btn-info" onclick="loading()">Voltar</div>', Url::to(['usuario/index'])); ?>
            
            <?php 
                if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                    echo Html::a('<div class="btn btn-warning" onclick="loading()">Alterar</div>', Url::to(['usuario/update','id'=>$model->id])); 
                }else if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO){
                    if($login->user_lvl != Logincerebrum::USUARIO_ADM){
                        echo Html::a('<div class="btn btn-warning" onclick="loading()">Alterar</div>', Url::to(['usuario/update','id'=>$model->id])); 
                    }
                }
            ?>

        </fieldset>

    <?php ActiveForm::end(); ?>

</div>