models/Operacao.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "operacao".
 *
 * @property int $id
 * @property string $nome
 * @property string $municipio_desc
 * @property int $municipio_id
 * @property int $orgao_responsavel_id
 * @property string $dt_referencia
 * @property string $hr_referencia
 * @property int $usuario_id
 *
 * @property Observacao[] $observacaos
 * @property Orgao $orgaoResponsavel
 * @property Usuario $usuario
 * @property ProdutividadeOperacao[] $produtividadeOperacaos
 * @property RecursoOperacao[] $recursoOperacaos
 */
class Operacao extends \yii\db\ActiveRecord
{

    public $nome_aux;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'operacao';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['municipio_id', 'orgao_responsavel_id'], 'integer'],
            [['dt_referencia', 'hr_referencia','nome','orgao_responsavel_id', 'usuario_id'], 'required'],
            [['nome'], 'string', 'max' => 100],
            [['municipio_desc', 'dt_referencia', 'hr_referencia'], 'string', 'max' => 45],
            [['orgao_responsavel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Orgao::className(), 'targetAttribute' => ['orgao_responsavel_id' => 'id']],
            [['usuario_id'], 'exist', 'skipOnError' => true, 'targetClass' => Usuario::className(), 'targetAttribute' => ['usuario_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nome' => 'Nome da Operação',
            'municipio_desc' => 'Município Descrição',
            'municipio_id' => 'Município',
            'orgao_responsavel_id' => 'Órgão Organizador',
            'dt_referencia' => 'Data Referência',
            'hr_referencia' => 'Hora Referência',
            'usuario_id' => 'Usuário',
            'nome_aux' => 'Usuário Responsável'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObservacaos()
    {
        return $this->hasMany(Observacao::className(), ['operacao_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrgaoResponsavel()
    {
        return $this->hasOne(Orgao::className(), ['id' => 'orgao_responsavel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(Usuario::className(), ['id' => 'usuario_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProdutividadeOperacaos()
    {
        return $this->hasMany(ProdutividadeOperacao::className(), ['operacao_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecursoOperacaos()
    {
        return $this->hasMany(RecursoOperacao::className(), ['operacao_id' => 'id']);
    }
}

controllers/OperacaoController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Operacao;
use app\models\OperacaoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Usuario;
use app\models\Localidade;
use app\models\Produtividadeoperacao;
use app\models\Recursooperacao;
use app\models\Relatorio;

/**
 * OperacaoController implements the CRUD actions for Operacao model.
 */
class OperacaoController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout','create','index','delete','update','view','viewallprodutividades','viewallrecursos','relatoriogeral'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create','view','index','delete','update','viewallprodutividades','viewallrecursos','relatoriogeral'],
                        'matchCallback' => function($rule,$action){
                            if(!Yii::$app->user->isGuest){
                                // echo "<pre>"; print_r(Yii::$app->user->identity->user_level);die;
                                return true;
                                // if(Yii::$app->user->identity->user_lvl_di == 1){
                                //     return true;
                                // }else{
                                //     return false;
                                // }
                            }
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Operacao models.
     * @return mixed
     */
    public function actionIndex()
    {
        
        $searchModel = new OperacaoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Operacao model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $model->nome_aux = Usuario::find()->where(['id'=>$model->usuario_id])->one()->username;

        $produtividades = Produtividadeoperacao::getProdutividadeOperacaoEOrgao(
            $model->id,
            Usuario::findOne(Yii::$app->user->identity->usuario_id)->orgao_id
        );
        
        $localidades = Localidade::getLocalidadesOperacao($model->id);

        return $this->render('view-operacao-com-produtividade', [
            'model' => $model,
            'produtividades'=>$produtividades,
            'localidades' => $localidades
        ]);
    }

    public function actionRelatoriogeral($id){
        $model = $this->findModel($id);
        
        $relatorio = Relatorio::relatorioGeralOperacao($id);

        return $this->renderPartial('../relatorios/relatorio_geral', [
            'model' => $model,
            'relatorio'=>$relatorio
        ]);
    }

    public function actionViewallprodutividades($id){
        $operacao = $this->findModel($id);
        $produtividades = Produtividadeoperacao::find()->where(['operacao_id'=>$id])->all();

        return $this->render('view-all-produtividades', [
            'model' => $operacao,
            'produtividades' => $produtividades
        ]);
    }

    public function actionViewallrecursos($id){
        $model = $this->findModel($id);
        $recursos = Recursooperacao::getAllRecursosOperacao($model->id);

        return $this->render('view-all-recursos', [
            'model' => $model,
            'recursos' => $recursos
        ]);
    }

    /**
     * Creates a new Operacao model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Operacao();

        if(Yii::$app->request->post()){
            $model->load(Yii::$app->request->post());
            $model->usuario_id = Yii::$app->user->identity->usuario_id;
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Operacao model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);

        $model->nome_aux = Usuario::find()->where(['id'=>$model->usuario_id])->one()->username;

        // echo "<pre>"; print_r($model->nome_aux);die;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
        
    }

    /**
     * Deletes an existing Operacao model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } catch (\Throwable $th) {
            //throw $th;
        }
        return $this->redirect(['index','status'=>'400','message'=>'não foi possivel excluir']);
    }

    /**
     * Finds the Operacao model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Operacao the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Operacao::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/operacao/_form-alterar.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Orgao;
use app\models\Municipio;

/* @var $this yii\web\View */
/* @var $model app\models\Operacao */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operacao-form">
    <?php $form = ActiveForm::begin(); ?>
        <fieldset>
            <legend><h1>Alterar Operação</h1></legend>

            <div class="col-md-12">
                <div class="col-md-6">
                    <div class="row">
                        <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>     
                    </div>
                    <div class="row">
                        <?= $form->field($model, 'municipio_id')
                            ->dropDownList(
                                ArrayHelper::map(Municipio::find()->all(), 'id', 'nome'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Operacao[municipio_id]']    // options
                        ); ?>
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'orgao_responsavel_id')->textInput() ?>
                        <?= $form->field($model, 'orgao_responsavel_id')
                            ->dropDownList(
                                ArrayHelper::map(Orgao::find()->all(), 'id', 'sigla'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Operacao[orgao_responsavel_id]']    // options
                        ); ?>
                    </div>
                    <div class="row">

                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row">
                        <?= $form->field($model, 'nome_aux')->textInput(['disabled'=>true]) ?>     
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'dt_referencia')->textInput(['maxlength' => true]) ?>
                        <div class="form-group field-operacao-dt_referencia">
                            <label class="control-label" for="operacao-dt_referencia">Data Referência</label>
                            <input type="text" value="<?php echo $model->dt_referencia; ?>" id="operacao-dt_referencia" class="data form-control" name="Operacao[dt_referencia]" maxlength="45" aria-invalid="false">
                        </div>
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'hr_referencia')->textInput(['maxlength' => true]) ?>                     
                        <div class="form-group field-operacao-hr_referencia ">
                            <label class="control-label" for="operacao-hr_referencia">Hora Referência</label>
                            <input type="text" value="<?php echo $model->hr_referencia; ?>" id="operacao-hr_referencia" class=" hora form-control" name="Operacao[hr_referencia]" maxlength="45" aria-invalid="false">
                        </div>
                    </div>
                    
                    <div class="row">

                    </div>
                    
                </div>
                <div class="col-md-12">
                    <div class="row">

                    </div>
                </div>
            </div>
        </fieldset>

    <?php //echo $form->field($model, 'municipio_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<script src="../js/jquery-3.3.1.min.js" ></script>
<script src="../js/jquery.maskedinput.min.js" ></script>
<script>
    $(document).ready(function($){
        $('.data').mask("99/99/9999");
        $('.hora').mask("99:99");
    })
</script>

views/operacao/_form-novo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Orgao;
use app\models\Municipio;


/* @var $this yii\web\View */
/* @var $model app\models\Operacao */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operacao-form">
    <?php $form = ActiveForm::begin(); ?>
        <fieldset>
            <legend><h1>Cadastrar Operação</h1></legend>

            <div class="col-md-12">
                <div class="col-md-6">
                    <div class="row">
                        <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>     
                    </div>
                    <div class="row">
                        <?= $form->field($model, 'municipio_id')
                            ->dropDownList(
                                ArrayHelper::map(Municipio::find()->all(), 'id', 'nome'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Operacao[municipio_id]']    // options
                        ); ?>
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'orgao_responsavel_id')->textInput() ?>
                        <?= $form->field($model, 'orgao_responsavel_id')
                            ->dropDownList(
                                ArrayHelper::map(Orgao::find()->all(), 'id', 'sigla'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Operacao[orgao_responsavel_id]']    // options
                        ); ?>
                    </div>
                    
                </div>

                <div class="col-md-6">
                    <div class="row">
                        <?= $form->field($model, 'usuario_id')->textInput(['readOnly'=>true,'value'=>Yii::$app->user->identity->username]) ?>     
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'dt_referencia')->textInput(['maxlength' => true]) ?>
                        <div class="form-group field-operacao-dt_referencia">
                            <label class="control-label" for="operacao-dt_referencia">Data Referência</label>
                            <input type="text" id="operacao-dt_referencia" class="data form-control" name="Operacao[dt_referencia]" maxlength="45" aria-invalid="false">
                        </div>
                    </div>
                    <div class="row">
                        <?php //echo $form->field($model, 'hr_referencia')->textInput(['maxlength' => true]) ?>                     
                        <div class="form-group field-operacao-hr_referencia ">
                            <label class="control-label" for="operacao-hr_referencia">Hora Referência</label>
                            <input type="text" id="operacao-hr_referencia" class=" hora form-control" name="Operacao[hr_referencia]" maxlength="45" aria-invalid="false">
                        </div>
                    </div>
                </div>
                <div class="col-md-12">

                </div>
                
            </div>
        </fieldset>

    <?php //echo $form->field($model, 'municipio_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<script src="../js/jquery-3.3.1.min.js" ></script>
<script src="../js/jquery.maskedinput.min.js" ></script>
<script>
    $(document).ready(function($){
        $('.data').mask("99/99/9999");
        $('.hora').mask("99:99");
    })
</script>

views/operacao/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Operacao */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operacao-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'municipio_desc')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'municipio_id')->textInput() ?>

    <?= $form->field($model, 'orgao_responsavel_id')->textInput() ?>

    <?= $form->field($model, 'dt_referencia')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hr_referencia')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'usuario_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/operacao/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OperacaoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operacao-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nome') ?>

    <?= $form->field($model, 'municipio_desc') ?>

    <?= $form->field($model, 'municipio_id') ?>

    <?= $form->field($model, 'orgao_responsavel_id') ?>

    <?php // echo $form->field($model, 'dt_referencia') ?>

    <?php // echo $form->field($model, 'hr_referencia') ?>

    <?php // echo $form->field($model, 'usuario_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/operacao/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Operacao */

// $this->title = 'Create Operacao';
$this->params['breadcrumbs'][] = ['label' => 'Operações', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="operacao-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form-novo', [
        'model' => $model,
    ]) ?>

</div>

views/operacao/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\Municipio;
use app\models\Orgao;
use app\models\Logincerebrum;
use app\models\Usuario;


/* @var $this yii\web\View */
/* @var $searchModel app\models\OperacaoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Operações';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="operacao-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php if(!Yii::$app->user->isGuest):?>
            <?php if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM):?>
                <?= Html::a('Cadastrar Operação', ['create'], ['class' => 'btn btn-success']) ?>
            <?php endif;?>
        <?php endif;?>
    </p>
<?php

    if(!Yii::$app->user->isGuest){
        if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_COMUM){
            echo GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'class' => 'yii\grid\SerialColumn',
                        'contentOptions' => ['style' => 'width: 20px;', 'class' => 'text-center'],
                    ],
                    [
                        'attribute' => 'nome',
                        'headerOptions' => ['class' => 'text-center'],
                        'contentOptions' => ['style' => 'width: 70%; color:#337ab7;', 'class' => 'text-left'],
                    ],
                    // [
                    //     'attribute' => 'dt_referencia',
                    //     'headerOptions' => ['class' => 'text-center'],
                    //     'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                    // ],
                    [
                    'class' => 'yii\grid\ActionColumn',
                    'header'=>'Ações', 
                    'headerOptions' => ['width' => '80','style'=>'width: 30%; color:#337ab7;', 'class'=>'text-center'],
                    'template' => '{view} {alterar} {deletar}',
                    'buttons' => [
                            'view' => function($url,$model,$key){
                                    return Html::a('<div class="btn btn-info" onclick="loading()">Visualizar</div>', Url::to(['operacao/view','id'=>$key]));
                                
                            },
                            // 'alterar' => function($url,$model,$key){
                            //     if(Usuario::findOne(Yii::$app->user->identity->usuario_id)->orgao_id == 23){
                            //         return Html::a('<div class="btn btn-warning" onclick="loading()">alterar</div>', Url::to(['operacao/update','id'=>$key]));
                            //     }
                            // },
                            // 'deletar' => function($url,$model,$key){
                            //     if(Yii::$app->user->identity->id == $model->usuario_id){
                            //         return Html::a('<div class="btn btn-danger" onclick="loading()">Deletar</div>', Url::to(['#']));
                            //     }
                            // },
                        ],
                    ],
                ],
            ]); 
        }else{
            echo GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'class' => 'yii\grid\SerialColumn',
                        'contentOptions' => ['style' => 'width: 20px;', 'class' => 'text-center'],
                    ],
                    [
                        'attribute' => 'nome',
                        'headerOptions' => ['class' => 'text-center'],
                        'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                    ],
                    [
                        'attribute' => 'orgao_responsavel_id',
                        'headerOptions' => ['class' => 'text-center'],
                        'value'  => function ($data) {
                            return Orgao::findOne($data->orgao_responsavel_id)->sigla;
                        },
                        'contentOptions' => ['style' => 'width: 10%; color:#337ab7;', 'class' => 'text-left'],
                    ],
                    // [
                    //     'attribute' => 'municipio_id',
                    //     'headerOptions' => ['class' => 'text-center'],
                    //     'value'  => function ($data) {
                    //         return Municipio::findOne($data->municipio_id)->nome;
                    //     },
                    //     'contentOptions' => ['style' => 'width: 10%; color:#337ab7;', 'class' => 'text-left'],
                    // ],
                    [
                        'attribute' => 'dt_referencia',
                        'headerOptions' => ['class' => 'text-center'],
                        'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                    ],
                    [
                        'attribute' => 'hr_referencia',
                        'headerOptions' => ['class' => 'text-center'],
                        'contentOptions' => ['style' => 'width: 5%; color:#337ab7;', 'class' => 'text-left'],
                    ],    
                    [
                    'class' => 'yii\grid\ActionColumn',
                    'header'=>'Ações', 
                    'headerOptions' => ['width' => '80','style'=>'width: 30%; color:#337ab7;', 'class'=>'text-center'],
                    'template' => '{view} {alterar} {relatorio} {deletar}',
                    'buttons' => [
                            'view' => function($url,$model,$key){
                                    return Html::a('<div class="btn btn-info" onclick="loading()">Visualizar</div>', Url::to(['operacao/view','id'=>$key]));
                                
                            },
                            'alterar' => function($url,$model,$key){
                                if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                                    return Html::a('<div class="btn btn-warning" onclick="loading()">alterar</div>', Url::to(['operacao/update','id'=>$key]));
                                    return Html::a('<div class="btn btn-warning" onclick="loading()">alterar</div>', Url::to(['operacao/relatoriogeral','id'=>$key]));
                                }
                                // else if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM_ORGAO && 
                                //          Yii::$app->user->identity->usuario_id == $model->usuario_id){
                                //     return Html::a('<div class="btn btn-warning" onclick="loading()">alterar</div>', Url::to(['operacao/update','id'=>$key]));
                                // }
                            },
                            'relatorio' => function($url,$model,$key){
                                if(Yii::$app->user->identity->user_lvl == Logincerebrum::USUARIO_ADM){
                                    return Html::a('<div title="Relatório Geral" class="btn btn-success"><span class="glyphicon glyphicon-file"></span></div>', Url::to(['operacao/relatoriogeral','id'=>$key]),['target'=>'_blank']);
                                }
                            }
                        ],
                    ],
                ],
            ]); 
        }
    }
        

        
    ?>
</div>

views/operacao/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Operacao */

// $this->title = 'Update Operacao: ' . $model->id;
// $this->params['breadcrumbs'][] = ['label' => 'Operacaos', 'url' => ['index']];
// $this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = 'Update';
?>
<div class="operacao-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form-alterar', [
        'model' => $model,
    ]) ?>

</div>

views/operacao/view-all-produtividades.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\Municipio;
use app\models\Orgao;
use app\models\Usuario;
use app\models\Indicador;
use app\models\Localidade;


/* @var $this yii\web\View */
/* @var $searchModel app\models\OperacaoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Operações';
$this->params['breadcrumbs'][] = $this->title;
?>

        

<fieldset>
    <div class="col-md-12">
        <legend>Produtividades da Operação : <?php echo $model->nome; ?></legend>

        <?php if($produtividades):?>
            <?php foreach($produtividades as $prod): ?>
                <a target='_blank' href="<?php echo Url::to(['produtividadeoperacao/view','id'=>$prod->id])?>">
                    <div class="panel-group">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                
                                <p>
                                    <div class="col-md-12">
                                        <div class="col-md-3">
                                            <?php echo Orgao::findOne($prod->orgao_id)->descricao;?> | 
                                            <?php echo Usuario::findOne($prod->usuario_id)->username;?> |
                                        </div>
                                        
                                        <div class="col-md-3">
                                            <b>
                                                <?php echo Indicador::findOne($prod->indicador_id)->descricao;?> | 
                                                <?php echo Localidade::findOne($prod->localidade_id)->nome;?>
                                            </b> 
                                        </div>
                                        
                                        <div class="col-md-3">
                                            <b>Qtd: </b><?php echo $prod->qtd;?>
                                        </div>
                                        
                                        <div class="col-md-3">
                                            <?php echo $prod->data." - ".$prod->hora;?> 
                                        </div>
                                    </div>
                                    <br> 
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            <?php endforeach;?>
        <?php endif;?>
    </div>    
</fieldset>